spring:
  camunda-bpm-datasource:
    url: ${DATASOURCE_URL}
    username: camunda
    password: ${CAMUNDA_BPM_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL

camunda:
  bpm:
    authorization:
      enabled: true
    admin-user:
      id: ${CAMUNDA_BPM_ADMIN_USERNAME}
      password: ${CAMUNDA_BPM_ADMIN_PASSWORD}