spring:
  camunda-bpm-datasource:
    url: ${DATASOURCE_URL}
    username: sa
    password: sa
    driver-class-name: orh.h2.Driver
  liquibase:
    enabled: false

camunda:
  bpm:
    authorization:
      enabled: true
    admin-user:
      id: admin
      password: admin
